// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Construccion_II___App_API_Rest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorModelFilmModel", b =>
                {
                    b.Property<Guid>("ActorModelsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FilmModelsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ActorModelsId", "FilmModelsId");

                    b.HasIndex("FilmModelsId");

                    b.ToTable("FilmActor", (string)null);
                });

            modelBuilder.Entity("Construccion_II___App_API_Rest.Src.Actors.ActorModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("Construccion_II___App_API_Rest.Src.Films.FilmModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly>("PremierDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("ActorModelFilmModel", b =>
                {
                    b.HasOne("Construccion_II___App_API_Rest.Src.Actors.ActorModel", null)
                        .WithMany()
                        .HasForeignKey("ActorModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Construccion_II___App_API_Rest.Src.Films.FilmModel", null)
                        .WithMany()
                        .HasForeignKey("FilmModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
